{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973.o",
    "module": "policy",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ahngp3h5ujfn3phbbcn3gxk5fm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "policy-1.0.0.aar",
          "url": "policy-1.0.0.aar",
          "size": 121546,
          "sha512": "7e4d612b696aa74816015954fc662f4cbf051db6a55b2af5a4c5813a53e3cf1dcb3e201f71142a4c9f8013fd3c1cc441e2dff5bda842962fec7bc3efa01fac71",
          "sha256": "0888671c6dcbda46495ad812189b760de2e6d5fe36a0499648965e6d7877f441",
          "sha1": "e56e11e84a082327b8a2599e998aff3d4f9bd260",
          "md5": "e15466480def26cda5060d83fee06523"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.juchen973",
          "module": "protobuff-nano",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.lbe",
          "module": "matrix",
          "version": {
            "requires": "1.2.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "matrix",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.megatronking.stringfog",
          "module": "xor",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-1.0.0.aar",
          "url": "policy-1.0.0.aar",
          "size": 121546,
          "sha512": "7e4d612b696aa74816015954fc662f4cbf051db6a55b2af5a4c5813a53e3cf1dcb3e201f71142a4c9f8013fd3c1cc441e2dff5bda842962fec7bc3efa01fac71",
          "sha256": "0888671c6dcbda46495ad812189b760de2e6d5fe36a0499648965e6d7877f441",
          "sha1": "e56e11e84a082327b8a2599e998aff3d4f9bd260",
          "md5": "e15466480def26cda5060d83fee06523"
        }
      ]
    }
  ]
}
