{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973.o",
    "module": "matrix",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mvakhshe3neqpbi3um4xwajfyu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-1.0.0.aar",
          "url": "matrix-1.0.0.aar",
          "size": 95178,
          "sha512": "7f9bce50178a3a46949cb4dadaf3de79a3dc593d83b0bb30be7e3c5f228f2f04109414da43374f10912a39423abc7161ff3b46e541ef2fadd2eda2d330c3e7d8",
          "sha256": "97c5a5cd34ef1a44e4a65a8e4da87cb95fd3c16bf54eb1d758991eafa37e938f",
          "sha1": "f35e0c408a8c170f6e6630fb54e509286a966c0d",
          "md5": "4ee300184bf8e7569cf7a40fa7df94ba"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.juchen973",
          "module": "protobuff-nano",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.juchen973.extra",
          "module": "oaid_sdk",
          "version": {
            "requires": "1.0.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "oaid_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "matrix-1.0.0.aar",
          "url": "matrix-1.0.0.aar",
          "size": 95178,
          "sha512": "7f9bce50178a3a46949cb4dadaf3de79a3dc593d83b0bb30be7e3c5f228f2f04109414da43374f10912a39423abc7161ff3b46e541ef2fadd2eda2d330c3e7d8",
          "sha256": "97c5a5cd34ef1a44e4a65a8e4da87cb95fd3c16bf54eb1d758991eafa37e938f",
          "sha1": "f35e0c408a8c170f6e6630fb54e509286a966c0d",
          "md5": "4ee300184bf8e7569cf7a40fa7df94ba"
        }
      ]
    }
  ]
}
