{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973.o",
    "module": "policy",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wldyehk4yvfdhbyvfmyqvbgipm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "policy-1.0.1.aar",
          "url": "policy-1.0.1.aar",
          "size": 121547,
          "sha512": "56143dafcfdaefa35e91aa86ca55ae6600493d7610b63ffc64eb80b40ce3260e6ae2c32d646c379c9169612a7252d7b078a139500b438b24c7f3f9813bb55050",
          "sha256": "b6b9e3573cd9210375ecce479b10f0091d5bb87ca8be77b6e4b0e93766d3fce2",
          "sha1": "7bb3a34e300aab2ed592492d51cb9aa00d1ab6f9",
          "md5": "4c5f74a0c9b38cf87fd21ee0dd4cdeee"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.juchen973",
          "module": "protobuff-nano",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.juchen973.o",
          "module": "matrix",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.megatronking.stringfog",
          "module": "xor",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-1.0.1.aar",
          "url": "policy-1.0.1.aar",
          "size": 121547,
          "sha512": "56143dafcfdaefa35e91aa86ca55ae6600493d7610b63ffc64eb80b40ce3260e6ae2c32d646c379c9169612a7252d7b078a139500b438b24c7f3f9813bb55050",
          "sha256": "b6b9e3573cd9210375ecce479b10f0091d5bb87ca8be77b6e4b0e93766d3fce2",
          "sha1": "7bb3a34e300aab2ed592492d51cb9aa00d1ab6f9",
          "md5": "4c5f74a0c9b38cf87fd21ee0dd4cdeee"
        }
      ]
    }
  ]
}
