{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973",
    "module": "tracker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hm4ikmavpfeffaj56jkiy3hbee"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lbe",
          "module": "matrix",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.juchen973.extra",
          "module": "thinkingsdk",
          "version": {
            "requires": "2.7.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "thinkingsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "tracker-1.0.0.aar",
          "url": "tracker-1.0.0.aar",
          "size": 51114,
          "sha512": "76986f1c05c1c78c7117c9f7bdfb9d6e228f3e093413325f0a5217ba6dafc3ba3bf3f81ecc64e3a680ccc754d0e55cc3dcda2c0ab1f5db2ddcbce6b018594470",
          "sha256": "bae0b18e9b491f90ed196879ce0df89c3f2aae84f21aba78d83681d6c0e9b232",
          "sha1": "f9b4d77762cac9c770b74d83b3ca53dbbd7539a4",
          "md5": "09cbb46c4b57888d226e20175f9633c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.lbe",
          "module": "matrix",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.juchen973.extra",
          "module": "thinkingsdk",
          "version": {
            "requires": "2.7.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "thinkingsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "tracker-1.0.0.aar",
          "url": "tracker-1.0.0.aar",
          "size": 51114,
          "sha512": "76986f1c05c1c78c7117c9f7bdfb9d6e228f3e093413325f0a5217ba6dafc3ba3bf3f81ecc64e3a680ccc754d0e55cc3dcda2c0ab1f5db2ddcbce6b018594470",
          "sha256": "bae0b18e9b491f90ed196879ce0df89c3f2aae84f21aba78d83681d6c0e9b232",
          "sha1": "f9b4d77762cac9c770b74d83b3ca53dbbd7539a4",
          "md5": "09cbb46c4b57888d226e20175f9633c0"
        }
      ]
    }
  ]
}
