{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973",
    "module": "tracker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hk2d2rpgc5dp7izblbod2vrmt4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lbe",
          "module": "matrix",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.juchen973.extra",
          "module": "thinkingsdk",
          "version": {
            "requires": "2.7.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "thinkingsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "tracker-1.0.0.aar",
          "url": "tracker-1.0.0.aar",
          "size": 50991,
          "sha512": "cb5fb1de0605382686b1369af5cf292b0042f1c196e5204a86e8fe2e0d7052736d4992e5a975d6bddc1736095b0c7fa43cc4f2765785e669e214cd80004eaa2f",
          "sha256": "c571ec1d69c930a572baf5e79d227534af725636334f7ee1548e58b3159f9e17",
          "sha1": "f70eb5d9b20d3f2f7a3df4fee421565d1051a2a4",
          "md5": "b9a7c63cb48a2ac7264ef76121d817ef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.lbe",
          "module": "matrix",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.juchen973.extra",
          "module": "thinkingsdk",
          "version": {
            "requires": "2.7.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "thinkingsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "tracker-1.0.0.aar",
          "url": "tracker-1.0.0.aar",
          "size": 50991,
          "sha512": "cb5fb1de0605382686b1369af5cf292b0042f1c196e5204a86e8fe2e0d7052736d4992e5a975d6bddc1736095b0c7fa43cc4f2765785e669e214cd80004eaa2f",
          "sha256": "c571ec1d69c930a572baf5e79d227534af725636334f7ee1548e58b3159f9e17",
          "sha1": "f70eb5d9b20d3f2f7a3df4fee421565d1051a2a4",
          "md5": "b9a7c63cb48a2ac7264ef76121d817ef"
        }
      ]
    }
  ]
}
