{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973",
    "module": "walle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bhgwpykpdjclrcvxklzbh6k7ba"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "walle-1.0.0.aar",
          "url": "walle-1.0.0.aar",
          "size": 10980,
          "sha512": "247015e2f33005669f5328bf0c825f80055b139e2779ed811dbb6b8878b6f79012e3041addb954a1d438971860e852f713faee1abf5f36267aab233f0223384c",
          "sha256": "907e91c310f5e3ea413c187a1b77fba20d1696e73dcdc6f8e41e21f20d543ced",
          "sha1": "8d9d9cb90201ef593cb91ffc04296305f48bf830",
          "md5": "cde041373b046f600a5aa0f40ed1f1cb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "walle-1.0.0.aar",
          "url": "walle-1.0.0.aar",
          "size": 10980,
          "sha512": "247015e2f33005669f5328bf0c825f80055b139e2779ed811dbb6b8878b6f79012e3041addb954a1d438971860e852f713faee1abf5f36267aab233f0223384c",
          "sha256": "907e91c310f5e3ea413c187a1b77fba20d1696e73dcdc6f8e41e21f20d543ced",
          "sha1": "8d9d9cb90201ef593cb91ffc04296305f48bf830",
          "md5": "cde041373b046f600a5aa0f40ed1f1cb"
        }
      ]
    }
  ]
}
