{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973.o",
    "module": "sharedprefer",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wprkntfs25aqxnjeolpbadqjei"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sharedprefer-1.0.4.aar",
          "url": "sharedprefer-1.0.4.aar",
          "size": 55779,
          "sha512": "a845618b9e8603aea51d45a16482b26e541e91d257d4619f7f0de277d33b5c5b3a0bea95faaffd7f9add0321afde852badf35ede5a1cf6c12d0f4499f0c5dab4",
          "sha256": "589a0f2b2e0be253918b0257da53c731ac3882a53eb325dcf5f3ab34e8638f32",
          "sha1": "8691cde3214ef2afda9058b0736724c46c640c50",
          "md5": "919737936c3a7b3561b74c30d9a9b496"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.juchen973",
          "module": "protobuff-nano",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "sharedprefer-1.0.4.aar",
          "url": "sharedprefer-1.0.4.aar",
          "size": 55779,
          "sha512": "a845618b9e8603aea51d45a16482b26e541e91d257d4619f7f0de277d33b5c5b3a0bea95faaffd7f9add0321afde852badf35ede5a1cf6c12d0f4499f0c5dab4",
          "sha256": "589a0f2b2e0be253918b0257da53c731ac3882a53eb325dcf5f3ab34e8638f32",
          "sha1": "8691cde3214ef2afda9058b0736724c46c640c50",
          "md5": "919737936c3a7b3561b74c30d9a9b496"
        }
      ]
    }
  ]
}
