{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juchen973.o",
    "module": "sharedprefer",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gfetlf7tnnbvxd2jmbvnbuldae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "sharedprefer-1.0.4.aar",
          "url": "sharedprefer-1.0.4.aar",
          "size": 2158,
          "sha512": "e6074a3b4be2b2088225025fa953384f88a1b25cc455833c31cc6a5b3d2e1fe4afdfbf4c757f93f35b5442b8c2f3743c773db988029524b471a44771e4624b47",
          "sha256": "b994522e09ade30fb04015bed4fde2472dcb3e6e5336cdf2b42d2209fc5dfe00",
          "sha1": "c74ffb14773e65845373491cbbe97eec98821707",
          "md5": "5c9880238c17e2b1c6299eb1155a9b66"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.juchen973",
          "module": "protobuff-nano",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "sharedprefer-1.0.4.aar",
          "url": "sharedprefer-1.0.4.aar",
          "size": 2158,
          "sha512": "e6074a3b4be2b2088225025fa953384f88a1b25cc455833c31cc6a5b3d2e1fe4afdfbf4c757f93f35b5442b8c2f3743c773db988029524b471a44771e4624b47",
          "sha256": "b994522e09ade30fb04015bed4fde2472dcb3e6e5336cdf2b42d2209fc5dfe00",
          "sha1": "c74ffb14773e65845373491cbbe97eec98821707",
          "md5": "5c9880238c17e2b1c6299eb1155a9b66"
        }
      ]
    }
  ]
}
